// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGdeQ7A2qsaZfz-n3gPYCt_q9Ra0FmOA',
    appId: '1:662608936310:web:5eed9fd27d3ce23f490e57',
    messagingSenderId: '662608936310',
    projectId: 'bykak-e4aab',
    authDomain: 'bykak-e4aab.firebaseapp.com',
    storageBucket: 'bykak-e4aab.appspot.com',
    measurementId: 'G-VBV4Q5T0D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8znfXdchnn0qYCtivVZOhKihESGNr4XI',
    appId: '1:662608936310:android:8f466df2ef6dcf1c490e57',
    messagingSenderId: '662608936310',
    projectId: 'bykak-e4aab',
    storageBucket: 'bykak-e4aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeirWoVGekKsBEgPBbj8PodNTUVY61gX8',
    appId: '1:662608936310:ios:1476c48af4010be3490e57',
    messagingSenderId: '662608936310',
    projectId: 'bykak-e4aab',
    storageBucket: 'bykak-e4aab.appspot.com',
    iosClientId: '662608936310-q9fdkmk7gk16ed4qj9r64jmv710hkf0e.apps.googleusercontent.com',
    iosBundleId: 'com.designer.bykak',
  );
}
